language: node_js
node_js:
  - node
matrix:
  fast_finish: true
install:
  - npm install
script:
  - tsc -V
  - npm run build
  - npm run build-lib
deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: docs
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true

  - provider: npm
    skip_cleanup: true
    before_deploy:
      - cd ./dist
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    on:
      tags: true
cache:
  directories:
    - node_modules
