language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm run build-lib

# 发布到npm
after_script:
  - bash ./npmpublish.sh

deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: docs
    github_token: $GITHUB_TOKEN
    on:
      tags: true
