language: node_js
node_js:
  - node
matrix:
  fast_finish: true
install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
script:
  - npm run build
  - npm run build-lib
deploy:
  - provider: pages
    skip-cleanup: true
    target-branch: gh-pages
    local-dir: docs
    email: gzlock88@gmail.com
    api_key:
      github_token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true

  - provider: npm
    before_deploy:
      - cd ./dist
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    skip_cleanup: true
    on:
      tags: true
cache:
  directories:
    - node_modules
