language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm run build-lib

# 发布前整理编译后的js脚本文件
before_deploy:
  - node after_build.js

# 发布到npm
after_deploy:
  - bash ./npmpublish.sh

# 发布到github pages
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    token: $GITHUB_TOKEN
    on:
      tags: true
