language: node_js
node_js:
  - node
matrix:
  fast_finish: true
install:
  - npm install
script:
  - npm run build
  - npm run build-lib

env:
  - TRAVIS_TAG=0.0.3

deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: docs
    github_token: $GITHUB_TOKEN

  - provider: npm
    skip_cleanup: true
    before_deploy:
      - bash ./npmpublish.sh $TRAVIS_TAG
      - cd ./dist
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    on:
      tags: true

cache:
  directories:
    - node_modules
