language: node_js
node_js:
- node
matrix:
  fast_finish: true
install:
- npm uninstall typescript --no-save
- npm uninstall tslint --no-save
- npm install
script:
- npm run build-lib

deploy:
  provider: npm
  email: gzlock88@gmail.com
  api_key:
    secure: SF8GAuCtgXsHDAjQmkQYY8MXe2EoWGMPHmLxPPY0TtobKgMqgl/feaA9GPZ0HYuEZeSQ/ZLiJZ5HE44dIDpchpYJOuetqF/TMDIc0ZfWxDFTSTC+XRiLd/3PN9sTK15cljdAhkyR8g0ZKYeJPeL40G8XNAD3om/q1rm4Cy3lX/rZqKNOlWKFb9oRHkHwb1sGHZxEi2MNoLnXl9nMJnexsVOZE+s8TT8rIkKVP1JnsnEbqjyOfHI+OWAK3UpJtosA/bJNuCfIl3I0avmsXRCP8yw1HbmQ7eY5EfWHsJ+h6WYqF6Go1jgiMEQZeczckWTX9841z8xEBpMLdIx2XMG8XHE3slSx76y5Pgrw/FYHg3l6HWiiOz7ajvb3X8INj95tWG5O4kAfEzkPql/vUdnWG0dOJXhDBgEbO/Nn6IWaq/UpD4TAX55aed2kFqBMGsfib1vyJCgM1fkwCAp1qwAFzUqjHjubfMuG7/aVlGSPspCqPvx4cVbEUPYGDkAHB9M4fCSEUJmMfMpmwZoxjnpNXs7Rho65vxw66zMG94jOwBiVCf2vZptZ4sE7PA+B2STc7VjbroikyMUS7lV8u9aaTm/tBGYYk74P3GQu0667bn6f8w9+Y/hdmStLrfCw9WgUlyslyJ8XCZT0IEtA3Z8lZCoUhBPejR9caKhjYPpo4vg=
  on:
    tags: true
cache:
  directories:
  - node_modules
